### ISSUE TITLE
bug: StringRevealer replace mutable property by default value

### ISSUE THREAD

**Issue by ultranity** [ben-sb/obfuscator-io-deobfuscator#5]
module StringRevealer

object default value should not be replaced globally if it 

example:
```
a = {
1: ""
}
a[1] = 2

let b = a[1]
```

current transform result:
```
let b = “”
```

expected:
check if  property is mutable(?)  and skip StringRevealer for them

**Comment by ben-sb** [comment]
Unfortunately there isn't a good way to tell with 100% certainty if a property is mutated (as property keys can be generated at runtime e.g. it is unclear which property is being accessed in `a[someFunction()]`).

What you can do is detect when the overall object is modified, and not replace anything in that case. This is available by setting `config.objectSimplification.unsafeReplace` to false).

**Comment by ultranity** [comment]
thanks for your explaination~
