### ISSUE TITLE
What have you done bro

### ISSUE THREAD

**Issue by AZERTY442005** [ben-sb/obfuscator-io-deobfuscator#9]
What have you done bro
Imagine using the basic Javascript Obfuscator to prevent people stealing your code....

**Comment by emeremikwu** [comment]
idk man, I like looking at other websites to see how they work. For me it's a learning experience

**Comment by ben-sb** [comment]
> What have you done bro Imagine using the basic Javascript Obfuscator to prevent people stealing your code....

What?

**Comment by umasii** [comment]
> What have you done bro Imagine using the basic Javascript Obfuscator to prevent people stealing your code....

What?
